### ISSUE TITLE
Any documentation on how to use this GEM

### ISSUE THREAD

**Issue by velu76** [klenis/multi-select-rails#1]
Hi,

I am trying to use your GEM. Though I got it working, I ran into troubles when I am tried to edit an existing record using multi-select.

Is there any documentation or tutorial that I can use?

Please assist.

Thank you.

**Comment by klenis** [comment]
The usage is pretty straightforward. On my applications I use the following:

In the view (using SimpleForm)

```
<%= f.association :users, :input_html => { "data-multi-select" => true } %>
```

In Javascript (using CoffeeScript)

```
$ ->
  $("select[data-multi-select=true]").each ->
    $(@).multiSelect()
```
